/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planalimenticio;

import java.awt.event.KeyEvent;

/**
 *
 * @author Miguel
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     * 
     */
    public Interfaz() {
        initComponents();
        pnlresultados.hide();
    }
    double IMC,PGC,MCM,TMB,CxD,PxD;
    Operaciones obj = new Operaciones();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngsexo = new javax.swing.ButtonGroup();
        lbltitulo = new javax.swing.JLabel();
        pnldatos = new javax.swing.JPanel();
        lblaltura = new javax.swing.JLabel();
        txtaltura = new javax.swing.JTextField();
        lblpeso = new javax.swing.JLabel();
        txtcintura = new javax.swing.JTextField();
        lblcintura = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        lblcuello = new javax.swing.JLabel();
        txtcuello = new javax.swing.JTextField();
        lblcadera = new javax.swing.JLabel();
        txtcadera = new javax.swing.JTextField();
        lblsexo = new javax.swing.JLabel();
        rbtnmasculino = new javax.swing.JRadioButton();
        rbtnfemenino = new javax.swing.JRadioButton();
        lblnivelact = new javax.swing.JLabel();
        cmbnivelact = new javax.swing.JComboBox<>();
        btncalcular = new javax.swing.JButton();
        pnlresultados = new javax.swing.JPanel();
        lblcxd = new javax.swing.JLabel();
        lblpxd = new javax.swing.JLabel();
        lblcalorias = new javax.swing.JLabel();
        lblproteinas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("Plan Alimenticio");

        lblaltura.setText("Altura (CM):");

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        txtaltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtalturaKeyTyped(evt);
            }
        });

        lblpeso.setText("Peso(KG):");

        txtcintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcinturaKeyTyped(evt);
            }
        });

        lblcintura.setText("Cintura(CM):");

        txtpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesoActionPerformed(evt);
            }
        });
        txtpeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpesoKeyTyped(evt);
            }
        });

        lblcuello.setText("Cuello(CM):");

        txtcuello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuelloActionPerformed(evt);
            }
        });
        txtcuello.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcuelloKeyTyped(evt);
            }
        });

        lblcadera.setText("Cadera(CM):");

        txtcadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaderaKeyTyped(evt);
            }
        });

        lblsexo.setText("Sexo:");

        btngsexo.add(rbtnmasculino);
        rbtnmasculino.setText("Masculino");
        rbtnmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmasculinoActionPerformed(evt);
            }
        });

        btngsexo.add(rbtnfemenino);
        rbtnfemenino.setText("Femenino");

        lblnivelact.setText("Nievel de actividad:");

        cmbnivelact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentario", "Ligero", "Moderado", "Intensa" }));
        cmbnivelact.setSelectedItem("");
        cmbnivelact.setToolTipText("");

        javax.swing.GroupLayout pnldatosLayout = new javax.swing.GroupLayout(pnldatos);
        pnldatos.setLayout(pnldatosLayout);
        pnldatosLayout.setHorizontalGroup(
            pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldatosLayout.createSequentialGroup()
                        .addComponent(lblnivelact)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnldatosLayout.createSequentialGroup()
                            .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblaltura)
                                .addComponent(lblpeso)
                                .addComponent(lblcintura)
                                .addComponent(lblcuello)
                                .addComponent(lblcadera))
                            .addGap(18, 18, 18)
                            .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcadera)
                                    .addComponent(txtcuello)
                                    .addComponent(txtcintura, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addComponent(txtpeso)
                                .addComponent(txtaltura, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldatosLayout.createSequentialGroup()
                            .addComponent(lblsexo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnfemenino)
                                .addComponent(rbtnmasculino)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldatosLayout.createSequentialGroup()
                            .addComponent(cmbnivelact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)))))
        );
        pnldatosLayout.setVerticalGroup(
            pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldatosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaltura)
                    .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpeso)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcintura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcuello)
                    .addComponent(txtcuello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcadera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsexo)
                    .addComponent(rbtnmasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnfemenino)
                .addGap(18, 18, 18)
                .addComponent(lblnivelact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbnivelact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lblcxd.setText("Calorias por dia:");

        lblpxd.setText("Proteinas por dia:");

        jLabel1.setText("Resultados");

        jLabel2.setText("IMC:");

        javax.swing.GroupLayout pnlresultadosLayout = new javax.swing.GroupLayout(pnlresultados);
        pnlresultados.setLayout(pnlresultadosLayout);
        pnlresultadosLayout.setHorizontalGroup(
            pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlresultadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblproteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(pnlresultadosLayout.createSequentialGroup()
                .addGroup(pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblpxd))
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(pnlresultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcxd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlresultadosLayout.setVerticalGroup(
            pnlresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlresultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcxd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpxd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblproteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lbltitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btncalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pnlresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbltitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pnlresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncalcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void rbtnmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnmasculinoActionPerformed
        
    private void txtpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpesoActionPerformed

    private void txtcuelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuelloActionPerformed

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    private void txtalturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalturaKeyTyped
        char c=evt.getKeyChar();
        if(c<'0' || c>'9') 
        evt.consume();
    }//GEN-LAST:event_txtalturaKeyTyped

    private void txtpesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesoKeyTyped
        char c=evt.getKeyChar();
        if(c<'0' || c>'9') 
        evt.consume();
    }//GEN-LAST:event_txtpesoKeyTyped

    private void txtcinturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcinturaKeyTyped
        char c=evt.getKeyChar();
        if(c<'0' || c>'9') 
        evt.consume();
    }//GEN-LAST:event_txtcinturaKeyTyped

    private void txtcuelloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcuelloKeyTyped
        char c=evt.getKeyChar();
        if(c<'0' || c>'9') 
        evt.consume();
    }//GEN-LAST:event_txtcuelloKeyTyped

    private void txtcaderaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaderaKeyTyped
        char c=evt.getKeyChar();
        if(c<'0' || c>'9') 
        evt.consume();
    }//GEN-LAST:event_txtcaderaKeyTyped

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        
        double altura,peso,cintura,cuello,cadera,nivelact=0;
        String sexo="",snivelact="";
        altura = Double.parseDouble(txtaltura.getText());
        peso = Double.parseDouble(txtpeso.getText());
        cintura = Double.parseDouble(txtcintura.getText());
        cuello = Double.parseDouble(txtcuello.getText());
        cadera = Double.parseDouble(txtcadera.getText());
        
        if(rbtnmasculino.isSelected())
            sexo="Masculino";
        else if(rbtnfemenino.isSelected())
            sexo="Femenino";
        
        snivelact=(String)cmbnivelact.getSelectedItem();
        System.out.println("SNIVEL"+snivelact+"V");
        switch(snivelact){
            case "Sedentario":nivelact=1.2;break;
            case "Ligero":nivelact=1.375;break;
            case "Moderado":nivelact=1.55;break;
            case "Intensa":nivelact=1.725;break;
                        }
        System.out.println("Nivel de act"+nivelact+snivelact);
        System.out.println("SEXO"+sexo);
        IMC= obj.IMC(peso,altura);
        PGC= obj.PGC(cintura, cuello, altura, cadera, sexo);
        MCM= obj.MCM(peso, PGC);
        TMB= obj.TMB(MCM);
        CxD= obj.CxD(TMB,nivelact);
        PxD= obj.PxD(peso);
        System.out.println("PGC"+PGC);
        lblIMC.setText(String.valueOf(Math.rint(IMC*100)/100));
        lblproteinas.setText(String.valueOf(Math.rint(PxD*100)/100));
        lblcalorias.setText(String.valueOf(Math.round(CxD)));
        pnlresultados.show();
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.ButtonGroup btngsexo;
    private javax.swing.JComboBox<String> cmbnivelact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblaltura;
    private javax.swing.JLabel lblcadera;
    private javax.swing.JLabel lblcalorias;
    private javax.swing.JLabel lblcintura;
    private javax.swing.JLabel lblcuello;
    private javax.swing.JLabel lblcxd;
    private javax.swing.JLabel lblnivelact;
    private javax.swing.JLabel lblpeso;
    private javax.swing.JLabel lblproteinas;
    private javax.swing.JLabel lblpxd;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnldatos;
    private javax.swing.JPanel pnlresultados;
    private javax.swing.JRadioButton rbtnfemenino;
    private javax.swing.JRadioButton rbtnmasculino;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtcadera;
    private javax.swing.JTextField txtcintura;
    private javax.swing.JTextField txtcuello;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
